-- 재적재 결과 대조 — 읽기 전용 (2026-09-10)
-- 예상값: 챕터 8개 · 하472 중436 상244 · 유형 331종 · SOURCE_ID 1,132건
SET PAGESIZE 200 LINESIZE 170 FEEDBACK OFF
COL WHAT FORMAT A26
COL TITLE FORMAT A20
COL DESCRIPTION FORMAT A20

PROMPT === ① 건수 ===
SELECT 'CHAPTERS' WHAT, COUNT(*) N FROM CHAPTERS
UNION ALL SELECT 'PROBLEMS(REAL)', COUNT(*) FROM PROBLEMS WHERE SOURCE_TYPE='REAL'
UNION ALL SELECT 'TOPIC 채워진 문제', COUNT(*) FROM PROBLEMS WHERE TOPIC IS NOT NULL
UNION ALL SELECT 'TOPIC 고유값(유형)', COUNT(DISTINCT TOPIC) FROM PROBLEMS
UNION ALL SELECT 'SOURCE_ID 채워진 문제', COUNT(*) FROM PROBLEMS WHERE SOURCE_ID IS NOT NULL
UNION ALL SELECT 'SOURCE_ID 고유값', COUNT(DISTINCT SOURCE_ID) FROM PROBLEMS;

PROMPT
PROMPT === ② 난이도 분포 (예상 하472 중436 상244) ===
SELECT DIFFICULTY, COUNT(*) N FROM PROBLEMS WHERE SOURCE_TYPE='REAL' GROUP BY DIFFICULTY ORDER BY 1;

PROMPT
PROMPT === ③ 챕터별 — 순번·제목·설명·문제수·난이도 ===
SELECT c.ORDER_NUM, c.TITLE, c.DESCRIPTION,
       COUNT(p.ID) 문제,
       SUM(CASE WHEN p.DIFFICULTY='LOW' THEN 1 ELSE 0 END) 하,
       SUM(CASE WHEN p.DIFFICULTY='MEDIUM' THEN 1 ELSE 0 END) 중,
       SUM(CASE WHEN p.DIFFICULTY='HIGH' THEN 1 ELSE 0 END) 상,
       COUNT(DISTINCT p.TOPIC) 유형
  FROM CHAPTERS c LEFT JOIN PROBLEMS p ON p.CHAPTER_ID = c.ID
 GROUP BY c.ORDER_NUM, c.TITLE, c.DESCRIPTION
 ORDER BY c.ORDER_NUM;

PROMPT
PROMPT === ④ 🔴 이름을 못 찾은 단원이 있나 (0건이어야 한다) ===
SELECT COUNT(*) 미등록단원 FROM CHAPTERS WHERE TITLE LIKE '(이름 미등록)%';

PROMPT
PROMPT === ⑤ 🔴 학생 자료 (재적재로 비워진 상태) ===
SELECT 'USERS' WHAT, COUNT(*) N FROM USERS
UNION ALL SELECT 'USER_PROBLEM_HISTORY', COUNT(*) FROM USER_PROBLEM_HISTORY
UNION ALL SELECT 'USER_CHAPTER_STATS', COUNT(*) FROM USER_CHAPTER_STATS;
EXIT
